services:
  backend:
    build: .
    ports:
      - "8001:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo
    container_name: cfyby-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: cfyby-mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: unless-stopped
    depends_on:
      - mongodb

volumes:
  mongo_data:
